<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB1y7p1v\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB1y7p1v/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerB1y7p1v.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerB1y7p1v\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerB1y7p1v\appProdProjectContainer([
    'container.build_hash' => 'B1y7p1v',
    'container.build_id' => '0db46ea6',
    'container.build_time' => 1610462234,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB1y7p1v');
