<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD3jv2c6\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD3jv2c6/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerD3jv2c6.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerD3jv2c6\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerD3jv2c6\appDevDebugProjectContainer([
    'container.build_hash' => 'D3jv2c6',
    'container.build_id' => '6946ff91',
    'container.build_time' => 1610434388,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD3jv2c6');
